# Generated by Django 4.2.30 on 2026-06-22 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地点名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, upload_to='travel/', verbose_name='图片')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=3, verbose_name='想去程度')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='城市/区域')),
                ('is_visited', models.BooleanField(default=False, verbose_name='已去过')),
                ('visited_photo', models.ImageField(blank=True, upload_to='travel/visited/', verbose_name='打卡照片')),
                ('visited_date', models.DateField(blank=True, null=True, verbose_name='打卡日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加者')),
            ],
            options={
                'verbose_name': '想去的地方',
                'verbose_name_plural': '想去的地方',
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='片名')),
                ('movie_type', models.CharField(choices=[('movie', '🎬 电影'), ('tv', '📺 电视剧'), ('variety', '🎭 综艺'), ('anime', '🎌 动漫')], default='movie', max_length=20, verbose_name='类型')),
                ('poster', models.ImageField(blank=True, upload_to='posters/', verbose_name='海报')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('status', models.CharField(choices=[('want', '想看'), ('watching', '在看'), ('done', '看完')], default='want', max_length=20, verbose_name='状态')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True, verbose_name='评分')),
                ('review', models.TextField(blank=True, verbose_name='评价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='添加者')),
            ],
            options={
                'verbose_name': '观影清单',
                'verbose_name_plural': '观影清单',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
