# Generated by Django 4.2.30 on 2026-06-22 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Whisper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='悄悄话')),
                ('image', models.ImageField(blank=True, upload_to='whispers/', verbose_name='图片')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名')),
                ('visible_at', models.DateTimeField(blank=True, help_text='留空则立即显示', null=True, verbose_name='定时显示')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '悄悄话',
                'verbose_name_plural': '悄悄话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', '🌅 早餐'), ('lunch', '☀️ 午餐'), ('dinner', '🌙 晚餐'), ('snack', '🍰 加餐')], max_length=20, verbose_name='餐次')),
                ('title', models.CharField(max_length=100, verbose_name='菜名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, upload_to='food/', verbose_name='照片')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='餐厅/地点')),
                ('date', models.DateField(verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '美食日记',
                'verbose_name_plural': '美食日记',
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='今天干了啥')),
                ('mood', models.CharField(blank=True, help_text='输入一个 emoji', max_length=10, verbose_name='心情')),
                ('image', models.ImageField(blank=True, upload_to='daily/', verbose_name='照片')),
                ('date', models.DateField(verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '每日日记',
                'verbose_name_plural': '每日日记',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
