# Generated by Django 4.2.30 on 2026-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_recalled",
            field=models.BooleanField(default=False, verbose_name="已撤回"),
        ),
    ]
