# Generated by Django 4.2.30 on 2026-06-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="已读"
            ),
        ),
    ]
